### ISSUE TITLE
Settings window options

### ISSUE THREAD

**Issue by yaccos** [biosustain/shu#45]
I notice that the hiding of irrelevant settings for the active data introduced by 36c5407949c01df9ebae553ef5d476c095d355e0 is a bit too aggressive. Currently, I am working on a Shu map with colored boxpoints accross four different conditions and the option `Zero as white` is missing from the menu as opposed to before.

**Comment by carrascomj** [comment]
Thanks! Should be fixed by 2bd0a45.
